import { readdir, readFile, writeFile } from 'fs/promises'
import { join } from 'path'
import { optimize } from 'svgo'
import svgToMiniDataURI from 'mini-svg-data-uri'

function convertToKebabCase(str: string): string {
  // Remove "Property=" prefix if it exists
  str = str.replace(/^Property=/, '')
  // Convert spaces and special characters to hyphens
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

async function buildIcons() {
  const iconsDir = join(process.cwd(), 'icons')
  const outputFile = join(process.cwd(), 'styles', 'icons.css')
  
  try {
    // Read all SVG files from the icons directory
    const files = await readdir(iconsDir)
    const svgFiles = files.filter(file => file.endsWith('.svg'))
    
    let cssContent = '/* This file was generated by build-icons.ts. Do not edit it manually. */\n'
    
    for (const file of svgFiles) {
      const iconName = convertToKebabCase(file.replace('.svg', ''))
      const svgContent = await readFile(join(iconsDir, file), 'utf-8')
      
      // Optimize SVG using svgo
      const result = optimize(svgContent, {
        path: file,
        multipass: true,
        plugins: [
          {
            name: 'preset-default',
            params: {
              overrides: {
                removeViewBox: false,
                convertColors: {
                  currentColor: true
                }
              }
            }
          }
        ]
      })
      
      // Convert SVG to data URL using mini-svg-data-uri
      const dataUrl = svgToMiniDataURI(result.data)
      
      // Generate CSS class
      cssContent += `
.i-${iconName} {
    display: inline-block;
    background-color: currentColor;
    -webkit-mask-image: var(--svg);
    mask-image: var(--svg);
    -webkit-mask-repeat: no-repeat;
    mask-repeat: no-repeat;
    -webkit-mask-size: 100% 100%;
    mask-size: 100% 100%;
    --svg: url("${dataUrl}");
}\n`
    }
    
    // Write the CSS file
    await writeFile(outputFile, cssContent.trim())
    console.log(`✅ Generated ${svgFiles.length} icons in ${outputFile}`)
  } catch (error) {
    console.error('Error building icons:', error)
    process.exit(1)
  }
}

buildIcons() 