/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SetupImport } from './routes/setup'
import { Route as IndexImport } from './routes/index'
import { Route as PostsIndexImport } from './routes/posts.index'
import { Route as PostsPostIdImport } from './routes/posts.$postId'

// Create/Update Routes

const SetupRoute = SetupImport.update({
	id: '/setup',
	path: '/setup',
	getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
	id: '/',
	path: '/',
	getParentRoute: () => rootRoute,
} as any)

const PostsIndexRoute = PostsIndexImport.update({
	id: '/posts/',
	path: '/posts/',
	getParentRoute: () => rootRoute,
} as any)

const PostsPostIdRoute = PostsPostIdImport.update({
	id: '/posts/$postId',
	path: '/posts/$postId',
	getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
	interface FileRoutesByPath {
		'/': {
			id: '/'
			path: '/'
			fullPath: '/'
			preLoaderRoute: typeof IndexImport
			parentRoute: typeof rootRoute
		}
		'/setup': {
			id: '/setup'
			path: '/setup'
			fullPath: '/setup'
			preLoaderRoute: typeof SetupImport
			parentRoute: typeof rootRoute
		}
		'/posts/$postId': {
			id: '/posts/$postId'
			path: '/posts/$postId'
			fullPath: '/posts/$postId'
			preLoaderRoute: typeof PostsPostIdImport
			parentRoute: typeof rootRoute
		}
		'/posts/': {
			id: '/posts/'
			path: '/posts'
			fullPath: '/posts'
			preLoaderRoute: typeof PostsIndexImport
			parentRoute: typeof rootRoute
		}
	}
}

// Create and export the route tree

export interface FileRoutesByFullPath {
	'/': typeof IndexRoute
	'/setup': typeof SetupRoute
	'/posts/$postId': typeof PostsPostIdRoute
	'/posts': typeof PostsIndexRoute
}

export interface FileRoutesByTo {
	'/': typeof IndexRoute
	'/setup': typeof SetupRoute
	'/posts/$postId': typeof PostsPostIdRoute
	'/posts': typeof PostsIndexRoute
}

export interface FileRoutesById {
	__root__: typeof rootRoute
	'/': typeof IndexRoute
	'/setup': typeof SetupRoute
	'/posts/$postId': typeof PostsPostIdRoute
	'/posts/': typeof PostsIndexRoute
}

export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath
	fullPaths: '/' | '/setup' | '/posts/$postId' | '/posts'
	fileRoutesByTo: FileRoutesByTo
	to: '/' | '/setup' | '/posts/$postId' | '/posts'
	id: '__root__' | '/' | '/setup' | '/posts/$postId' | '/posts/'
	fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
	IndexRoute: typeof IndexRoute
	SetupRoute: typeof SetupRoute
	PostsPostIdRoute: typeof PostsPostIdRoute
	PostsIndexRoute: typeof PostsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
	IndexRoute: IndexRoute,
	SetupRoute: SetupRoute,
	PostsPostIdRoute: PostsPostIdRoute,
	PostsIndexRoute: PostsIndexRoute,
}

export const routeTree = rootRoute._addFileChildren(rootRouteChildren)._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/setup",
        "/posts/$postId",
        "/posts/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/setup": {
      "filePath": "setup.tsx"
    },
    "/posts/$postId": {
      "filePath": "posts.$postId.tsx"
    },
    "/posts/": {
      "filePath": "posts.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
