import { Client } from '@modelcontextprotocol/sdk/client'
import type { Transport } from '@modelcontextprotocol/sdk/shared/transport.js'
import { NostrClientTransport, type NostrTransportOptions, PrivateKeySigner, ApplesauceRelayPool } from '@contextvm/sdk'

export interface GetBtcPriceInput {
	/**
	 * Force refresh of rates, bypassing the server cache
	 */
	refresh?: boolean
}

export interface GetBtcPriceOutput {
	/**
	 * BTC exchange rates per fiat currency
	 */
	rates: {
		[k: string]: number
	}
	/**
	 * Price sources that returned successfully
	 */
	sourcesSucceeded: string[]
	/**
	 * Price sources that failed
	 */
	sourcesFailed: string[]
	/**
	 * Unix timestamp (ms) when rates were fetched
	 */
	fetchedAt: number
	/**
	 * Whether the returned rates were served from cache
	 */
	cached: boolean
}

export interface GetBtcPriceSingleInput {
	/**
	 * ISO 4217 currency code, e.g. USD, EUR, JPY
	 */
	currency: string
	/**
	 * Force refresh of rates, bypassing the server cache
	 */
	refresh?: boolean
}

export interface GetBtcPriceSingleOutput {
	/**
	 * The requested currency code
	 */
	currency: string
	/**
	 * BTC exchange rate for the requested currency
	 */
	rate: number
	/**
	 * Unix timestamp (ms) when rates were fetched
	 */
	fetchedAt: number
	/**
	 * Whether the returned rate was served from cache
	 */
	cached: boolean
}

// Auction tool interfaces (RequestPath*, SubmitBidToken*, RequestSettlement*, GetAuctionState*)
// were generated by ctxcn against the v1 CVM auction tool family. Those tools
// were removed in Phase 2 of the bidder-held-path migration (AUCTIONS.md); only
// the currency tool interfaces remain here. Regenerate via ctxcn against the
// current server if you want a fresh round-trip.

export type PlebeianServer = {
	GetBtcPrice: (refresh?: boolean) => Promise<GetBtcPriceOutput>
	GetBtcPriceSingle: (currency: string, refresh?: boolean) => Promise<GetBtcPriceSingleOutput>
}

export class PlebeianServerClient implements PlebeianServer {
	static readonly SERVER_PUBKEY = '29bd6461f780c07b29c89b4df8017db90973d5608a3cd811a0522b15c1064f15'
	static readonly DEFAULT_RELAYS = ['ws://localhost:10547']
	private client: Client
	private transport: Transport

	constructor(options: Partial<NostrTransportOptions> & { privateKey?: string; relays?: string[] } = {}) {
		this.client = new Client({
			name: 'PlebeianServerClient',
			version: '1.0.0',
		})

		// Private key precedence: constructor options > config file
		const resolvedPrivateKey = options.privateKey || ''

		// Use options.signer if provided, otherwise create from resolved private key
		const signer = options.signer || new PrivateKeySigner(resolvedPrivateKey)
		// Use options.relays if provided, otherwise use class DEFAULT_RELAYS
		const relays = options.relays || PlebeianServerClient.DEFAULT_RELAYS
		// Use options.relayHandler if provided, otherwise create from relays
		const relayHandler = options.relayHandler || new ApplesauceRelayPool(relays)
		const serverPubkey = options.serverPubkey
		const { privateKey: _, ...rest } = options

		this.transport = new NostrClientTransport({
			serverPubkey: serverPubkey || PlebeianServerClient.SERVER_PUBKEY,
			signer,
			relayHandler,
			isStateless: true,
			...rest,
		})

		// Auto-connect in constructor
		this.client.connect(this.transport).catch((error) => {
			console.error(`Failed to connect to server: ${error}`)
		})
	}

	async disconnect(): Promise<void> {
		await this.transport.close()
	}

	// NOTE: HAND-EDIT after `bunx ctxcn add` — re-running ctxcn will
	// overwrite this back to the no-error-handling default. The error
	// detection below MUST be re-applied. Tracker:
	// https://github.com/ContextVM/ctxcn (file an issue if you want this
	// upstream).
	private async call<T = unknown>(name: string, args: Record<string, unknown>): Promise<T> {
		const result = await this.client.callTool({
			name,
			arguments: { ...args },
		})
		if (result.isError) {
			const message =
				typeof (result.structuredContent as { error?: unknown })?.error === 'string'
					? (result.structuredContent as { error: string }).error
					: `${name} returned isError but no structuredContent.error`
			throw new Error(message)
		}
		return result.structuredContent as T
	}

	/**
	 * Get BTC exchange rates for all supported fiat currencies. Aggregates from Yadio, CoinDesk, Binance, and CoinGecko with median calculation.
	 * @param {boolean} refresh [optional] Force refresh of rates, bypassing the server cache
	 * @returns {Promise<GetBtcPriceOutput>} The result of the get_btc_price operation
	 */
	async GetBtcPrice(refresh?: boolean): Promise<GetBtcPriceOutput> {
		return this.call('get_btc_price', { refresh })
	}

	/**
	 * Get the BTC exchange rate for a specific fiat currency.
	 * @param {string} currency ISO 4217 currency code, e.g. USD, EUR, JPY
	 * @param {boolean} refresh [optional] Force refresh of rates, bypassing the server cache
	 * @returns {Promise<GetBtcPriceSingleOutput>} The result of the get_btc_price_single operation
	 */
	async GetBtcPriceSingle(currency: string, refresh?: boolean): Promise<GetBtcPriceSingleOutput> {
		return this.call('get_btc_price_single', { currency, refresh })
	}

	// Auction methods (RequestPath, SubmitBidToken, RequestSettlement, GetAuctionState)
	// removed in Phase 2 of the bidder-held-path migration. Regenerate via ctxcn
	// against the current server to get an up-to-date method surface.
}
